#!/bin/bash
#SBATCH --job-name=train
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gpus-per-node=1
#SBATCH --mem=1000
#SBATCH --time=00:20:00
#SBATCH --output=train.out
#SBATCH --error=train.err
#SBATCH --partition=gpu

export OMP_NUM_THREADS=1

module load python/3.8.6
module load gcc/10.2.0
module load cuda/11.1.0 cudnn/8.1.1.33-11.2

source ~/Mobilise-D/envs/bin/activate

python ~/Mobilise-D/code/train.py
